name: Echo Branch Name

on:
  push:
    branches:
      - '*'

jobs:
  echo-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo Branch Name
      run: echo "The current branch is ${{ github.ref_name }}"
