name: run-test-cases
on: [push, pull_request]
jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:

      - name: Current branch names
        run: echo "Source branch is ${{ github.event.pull_request.head.ref }}"

