name: run-test-cases
on: [push, pull_request]
jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:

      - name: Current branch names
        run: |
          echo "${{ env.GITHUB_REF }}"
          echo "${{ env.GITHUB_HEAD_REF }}"
